export const POKEMON_LIST_ACTIONS = {
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    UPDATE_OFFSET: 'UPDATE_OFFSET',
    UPDATE_POKEMON_LIST: 'UPDATE_POKEMON_LIST',
    SET_HAS_MORE: 'SET_HAS_MORE',
    RESET_POKEMON_LIST: 'RESET_POKEMON_LIST',
    SET_POKEMON_ON_DISPLAY: 'SET_POKEMON_ON_DISPLAY'
}

export const LIMIT_INCREMENT = 20